NOTE: この章について
記念祭に関して会計班から団体に配布するお金には、大きく分けて二種類あります。一つ目は「配布金」、もう一つは「食物仕入金」。このそれぞれについて説明します。また、各クラスの文化的や部活動の会計担当が集まる「○○会」についてもまとめました。最後に、今年度の予定を記載してあります。

=== お金について
記念祭の予算には「配布金」と「食物仕入金」があります。このそれぞれについて説明します。

==== 配布金とは
各団体が、記念祭に必要なものを購入するために使用できるお金です。自治会費（生徒の家庭から集めたお金）より支出されています。昨年度の配布額と使用額を掲載します。配布額は1,000円単位です。


[IMPORTANT]
.TODO
====
ここに昨年度実績の表を掲載する
====

==== 食物仕入金とは
食物の販売を行う団体が、自治会費から借りるお金のことです。この借りたお金を使って、販売する商品を購入します。借りているお金であるため、返済しなければなりません。昨年度の団体別借入額は下の通りです。

[IMPORTANT]
.TODO
====
団体、購入品目、仕入れ単価、購入個数、借入額の表をここに掲載する
====

=== 説明会について
ここでは、記念祭の会計班が主催する説明会等について説明します。各団体の会計担当は必ず出席してください。（どうしても出席が難しい場合は代理を立てても構いませんが、情報を必ず伝えるようにしてください）

==== 会計セミナー
各団体の会計担当に記念祭の会計について説明したり、注意事項や提出書類の記入方法などについて説明します。
なお、会計会は自治会が主催するものなので、間違えないようにしてください。会計会の主な対象者は、部活動や委員会の会計担当です。

==== 打ち込み会
各団体が購入したものを、各団体の会計担当者がパソコン室で入力する会です。詳しくは、 link:打ち込み会[打ち込み会] を参照してください。

==== 精算会
パソコンに入力したデータと、購入したときのレシートの内容が完全に一致しているか確認します。また、手元に残っているお金と、使用したお金を合計した額が配布額と一致するかどうかも確認します。ここでミスが発覚すると、団体負担となることがあります。

=== 今後の予定
以下の表のとおりです。

[IMPORTANT]
.TODO
====
開催場所、持ち物の説明を入れる
====

[options="header"]
|===============================================
| 日付   | 種類     | 対象           | 内容             
| 4/-- | 会計セミナー | 全団体の会計担当者    | 会計Bookの配布・簡単な説明
| 5/-- | 会計セミナー | 全団体の会計担当者    | 補正予算について       
| 5/-- | 会計セミナー | 食物模擬団体の会計担当者 | 食物仕入金について      
|===============================================

